name: CI

on:
  schedule:
    - cron: "0 21,13 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run script
      run: python3 run.py
