name: OSS Projects

on:
  schedule:
    - cron: "0 17,9 * * *"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing setup-tools
      run: sudo apt-get install python3-setuptools
    - name: Install chromium-chromedriver
      run: sudo apt-get install chromium-chromedriver
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Install Python Package
      run: python3 setup.py install
    - name: Run script
      env: # Or as an environment variable
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        TWITTER_SECRET_KEY: ${{ secrets.TWITTER_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
        LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
        LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
        LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
      run: revivesocialmedia oss
